### ISSUE TITLE
add default users

### ISSUE THREAD

**Issue by umbros** [italia/spid-testenv-backoffice#1]
_From @umbros on October 2, 2017 22:32_

Add default user inside default users json: https://github.com/italia/spid-testenv-backoffice/blob/master/addons/user-import/spid-users.json

* Italian man
* Italian woman
* Man born outside Italy
* Woman bord outside Italy
* Heighteen years old boy
* Heighteen years old girl
* Underage boy
* Underage girl

_Copied from original issue: italia/spid-testenv-backoffice-old#2_

**Comment by damikael** [comment]
done
