### ISSUE TITLE
Errori XML metadata IdP

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv-backoffice#17]
Ci sono due cose da correggere nell'XML dell'IdP:

1. Nel tag `<EntityDescriptor>` va aggiunto l'attributo `xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"`
2. Il tag `<SingleLogoutService>`contiene uno slash di troppo alla fine dell'attributo `ResponseLocation`

Avrei inviato una pull request ma a quanto pare l'ambiente di test installato su https://idp.spid.gov.it:8080 non corrisponde ai contenuti di questo repository e non trovo il codice in questione.

**Comment by damikael** [comment]
Il codice sull'ambiente di test era relativo alla PR #15 che ancora non era stata inserita sul master.
Ho apportato le modifiche richieste sulla stessa PR #15
