### ISSUE TITLE
https richiesto per l'entity ID

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv-backoffice#18]
Il form di creazione di un Service Provider impone che l'entity ID inizi per `https`, ma secondo le regole tecniche è richiesto solo che sia una URI. L'ambiente di test quindi, se non erro, è più restrittivo delle regole tecniche e dovrebbe invece essere conforme.

**Comment by damikael** [comment]
N.B. Avviso 6 (http://www.agid.gov.it/sites/default/files/documentazione/spid-avviso-n6-note-sul-dispiegamento-di-spid-presso-i-gestori-di-servizi-v1.pdf):

> entityid - Per garantire l’univocità si consiglia di usare il nome di dominio registrato dall’ente od un suo sottodominio (Avviso 6 par 2.2)

**Comment by alexrj** [comment]
Tre osservazioni:

1. l'avviso dice "si consiglia", quindi l'ambiente di test dovrebbe fornire un warning, non un errore bloccante;
2. l'avviso parla di un nome di dominio, mentre l'ambiente di test richiede una URI (che è cosa diversa);
3. l'avviso non richiede `https`.

**Comment by alexrj** [comment]
Sì, quel consiglio è chiaro. Ma questa mia segnalazione era relativa alla restrizione su `https`: una URI che inizia con `http` dovrebbe essere accettata.

**Comment by alexrj** [comment]
This issue was moved to italia/spid-testenv#16
