### ISSUE TITLE
Errato salvataggio dei dati dell'utente creato per un Service Provider

### ISSUE THREAD

**Issue by cellamareg** [italia/spid-testenv-backoffice#22]
Ho inserito un utente collegato ad un Service Provider e quando inserisco i vari attributi (nome, cognome, etc..)ho riscontrato che viene salvato nel campo Data di Nascita l'ultimo valore di data inserita nella form, ossia tutti i campi di tipo DatePicker sono collegati alla stessa proprietà dateOfBirth invece delle proprietà corrispondenti.

**Comment by damikael** [comment]
Correzioni riportate sulla PR #23.
Grazie
